services:
  mock-service:
    build: .
    image: ssh-remote-box-mock
    container_name: ssh-remote-box-mock
    init: true  # Use tini as init process
    stop_signal: SIGTERM
    stop_grace_period: 2s
    ports:
      - '2222:22'
      - '2525:2525'  # Mountebank admin
      - '8080:8080'  # Mock API
    networks:
      - test-network
    tty: true
    volumes:
      - ssh-remote-box-mock_data:/data
      - ${PWD}/ssh_keys:/ssh_keys
      - ${PWD}/imposters:/imposters
    command: >
      /bin/bash -c "
      cat /ssh_keys/id_rsa.pub > /root/.ssh/authorized_keys &&
      chmod 600 /root/.ssh/authorized_keys &&
      trap 'kill -TERM $$(jobs -p) 2>/dev/null' TERM INT &&
      /usr/sbin/sshd &&
      mb --configfile /imposters/imposters.ejs --allowInjection &
      wait
      "

networks:
  test-network:
    driver: bridge

volumes:
  ssh-remote-box-mock_data: 